on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      NAME_HELM_FOLDER:
        required: true
        type: string
      URL_HELM_REPOSITORY:
        required: true
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
      TOKEN_HELM_STORE:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Docker Image name
        id: docker-image
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          IMAGE_NAME=${BRANCH_NAME}_${{ github.sha }}
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Extract Repo name
        id: extract-repository-name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT  

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: >
            ${{ inputs.DOCKERHUB_USERNAME }}/${{ steps.extract-repository-name.outputs.REPO_NAME }}:${{ steps.docker-image.outputs.IMAGE_NAME }}

      - name: Get Dockerhub Image sha256
        id: image-digest
        run: |
          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ inputs.DOCKERHUB_USERNAME }}/${{ steps.extract-repository-name.outputs.REPO_NAME }}:${{ steps.docker-image.outputs.IMAGE_NAME }}" | cut -d "@" -f 2)
          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> $GITHUB_OUTPUT

      - name: Setup yq portable command-line YAML processor
        uses: mikefarah/yq@v4.35.2

      - name: Update local Helm yaml Files
        run: |
          helm_folder="${{ inputs.NAME_HELM_FOLDER }}"
          version_helm="$(cat VERSION_HELM)"
          run_number="${{ github.run_number }}"
          image_name="${{ steps.docker-image.outputs.IMAGE_NAME }}"
          image_digest="${{ steps.image-digest.outputs.IMAGE_DIGEST }}"
          account="${{ inputs.DOCKERHUB_USERNAME }}"
          repo_name="${{ steps.extract-repository-name.outputs.REPO_NAME }}"
          
          yq -i ".version = \"${version_helm}.${run_number}\"" "./${helm_folder}/Chart.yaml"
          yq -i ".appVersion = \"$(cat VERSION)\"" "./${helm_folder}/Chart.yaml"
          
          yq -i '.image.repository = "'"${account}/${repo_name}"'"' "./${helm_folder}/values.yaml"
          yq -i '.image.tag = "'"${image_name}@${image_digest}"'"' "./${helm_folder}/values.yaml"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.1'

      - name: Package Helm Chart
        run: |
          helm package ./${{ inputs.NAME_HELM_FOLDER }}
          helm repo index ./${{ inputs.NAME_HELM_FOLDER }} --url ${{ inputs.URL_HELM_REPOSITORY }}

      - name: Checkout Helm Package Repo
        uses: actions/checkout@v3
        with:
          repository: djoksa4/helm-store 
          ref: pre-deployment
          token: '${{ secrets.TOKEN_HELM_STORE }}'
          path: ./helm-store

      - name: Copy Helm Package
        run: |
          mkdir -p helm-store/app/${{ steps.extract-repository-name.outputs.REPO_NAME }}
          cp *.tgz helm-store/app/${{ steps.extract-repository-name.outputs.REPO_NAME }}/

      - name: Commit and push changes to Helm Package Repo
        run: |
          cd helm-store/
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull origin pre-deployment
          git add .
          git commit -m "${{ github.ref_name }}"
          git push origin pre-deployment